version: '3'

services:
  flask_api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
    - db
  db:
    image: postgres:15.4-bookworm
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"